name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image

    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven

    - name: Restore Maven Cache
      uses: actions/cache@v2
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
     
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      run: docker build -t adeshianaqudus/BookEase:latest

    - name: push Docker image to Docker Hub
      run: docker push adeshianaqudus/BookEase:latest        
